#use_frameworks!

target 'AKModel_Example' do
  pod 'AKModel', :path => '../'
  pod 'AKSingleton', :git => 'git@github.com:ArtisanKid/AKSingleton.git'

  target 'AKModel_Tests' do
    inherit! :search_paths

    
  end
end
